### ISSUE TITLE
Primary key in inherited tables

### ISSUE THREAD

**Issue by nolith** [pacuna/partitionable#1]
Hi,

is it normal that the inherited table you create do not declare the primary key constraint?
I did some tests and was able to insert multiple rows with the same id.

I fixed it on my model redeclaring `self.create_table_statement(month, year)`

```ruby
  # preserve primary key on hinerited tables
  def self.create_table_statement(month, year)
    partition = partition_name(month, year)
    <<-SQL
      #{super(month, year)}
      ALTER TABLE ONLY #{partition}
        ADD CONSTRAINT #{partition}_pkey PRIMARY KEY (#{primary_key});
    SQL
  end
```

I can make a PR if you like.

**Comment by pacuna** [comment]
@nolith you're right! Please submit the PR.

Thanks!
